Repository idlesign/torrt, pull requests merged in 2019-02, with the labels that each got.

#27 Telegram bot
  MANIFEST.in
  docs/source/bot.rst
  docs/source/commands.rst
  docs/source/index.rst
  docs/source/toolbox.rst
  setup.py
  torrt/base_bot.py
  torrt/bots/__init__.py
  torrt/bots/telegram_bot.py
  torrt/main.py
  torrt/toolbox.py
  torrt/utils.py
Labels: enhancement

#31 Fixed Telegram notifier
  torrt/notifiers/telegram.py
Labels: bug

#32 Adopted new AniLibria.tv layout and improved quality matching algorithm for AnilibriaTracker
  tests/test_utils.py
  tests/trackers/__init__.py
  tests/trackers/test_anilibria.py
  torrt/trackers/anilibria.py
Labels: bug, enhancement
